#!/bin/bash

if [ $# -ne 1 ]; then
  echo "Usage: ./docker-startup <build/deploy/deploy-gpu>"
  exit 
fi

if [ "$1" = "build" ]; then
  docker build -t run-rag .
elif [ "$1" = "deploy" ]; then
  docker run --rm --name run-rag -v $PWD:/root -p 8501:8501 -it run-rag
elif [ "$1" = "deploy-gpu" ]; then
  docker run --rm --name run-rag -d --gpus=all -v $PWD:/root -p 8501:8501 -it run-rag
fi